spring.datasource.url=jdbc:postgresql://localhost:5432/wellnara

spring.datasource.username=${DB_USERNAME:wellnara_admin}
spring.datasource.password=${DB_PASSWORD}
wellnara.admin.password=${WELLNARA_ADMIN_PASSWORD}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

wellnara.admin.username=${WELLNARA_ADMIN_USERNAME:admin}
wellnara.admin.email=${WELLNARA_ADMIN_EMAIL:admin@wellnara.local}

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

wellnara.public-base-url=http://localhost:8080
wellnara.mail.from=wellnara-dev@wellnara.local

wellnara.invitation.ttl-days=7