-- =====================================================================
-- Wellnara — Flyway V13: password reset tokens
--
-- Backs the "forgot password" flow. One row per issued reset link: only the
-- token HASH is stored (the raw token lives solely in the emailed link), so a
-- database leak cannot be used to reset passwords. A token is single-use
-- (used_at set once consumed) and expires (expires_at).
--
-- Column types mirror Hibernate 6.5 / PostgreSQL output so ddl-auto=validate
-- matches the entity on prod:
--   - identity PK: bigint generated by default as identity
--   - timestamps: timestamp(6)
-- =====================================================================

create table password_reset_tokens (
    id         bigint generated by default as identity,
    user_id    bigint not null,
    token_hash varchar(255) not null,
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    used_at    timestamp(6),
    primary key (id),
    constraint uk_password_reset_tokens_token_hash unique (token_hash)
);

alter table password_reset_tokens
    add constraint fk_password_reset_tokens_user foreign key (user_id) references users;
