-- =====================================================================
-- Wellnara — Flyway baseline (step 2.1)
-- Snapshot of the schema Hibernate currently generates (ddl-auto=update),
-- PostgreSQL dialect (Spring Boot 3.3.2 / Hibernate ORM 6.5.x).
--
-- Rules from here on: NEVER edit this file. Every schema change is a new
-- V2__*.sql, V3__*.sql, ... migration. Prod runs ddl-auto=validate, so the
-- schema below must match the entities exactly.
--
-- IMPORTANT: verify this against the real Hibernate output before committing
-- (see the schema-generation command in the accompanying notes). Column types
-- (timestamp(6)/time(6)) and enum CHECK constraints follow Hibernate 6.5.
-- =====================================================================

create table users (
    id       bigint generated by default as identity,
    username varchar(255) not null,
    password varchar(255) not null,
    email    varchar(255) not null,
    role     varchar(255) not null check (role in ('ADMIN', 'PROVIDER', 'CLIENT')),
    primary key (id),
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email)
);

create table user_profiles (
    id         bigint generated by default as identity,
    user_id    bigint not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    phone      varchar(255),
    primary key (id),
    constraint uk_user_profiles_user unique (user_id)
);

create table offerings (
    id                bigint generated by default as identity,
    provider_id       bigint not null,
    name              varchar(255) not null,
    description       varchar(2000) not null,
    price_per_session numeric(10, 2) not null,
    duration_minutes  integer not null,
    active            boolean not null,
    primary key (id)
);

create table appointments (
    id                  bigint generated by default as identity,
    provider_id         bigint not null,
    client_id           bigint not null,
    offering_id         bigint not null,
    start_date_time_utc timestamp(6) not null,
    status              varchar(255) not null check (status in ('REQUESTED', 'CONFIRMED', 'PAYMENT_REQUESTED', 'REJECTED', 'CANCELLED_BY_PROVIDER', 'CANCELLED_BY_CLIENT', 'COMPLETED', 'NO_SHOW')),
    created_at          timestamp(6) not null,
    updated_at          timestamp(6) not null,
    rejection_reason    varchar(1000),
    primary key (id)
);

create table availability_periods (
    id                bigint generated by default as identity,
    provider_id       bigint not null,
    date_from         date not null,
    date_to           date not null,
    provider_timezone varchar(255) not null,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6) not null,
    primary key (id)
);

create table availability_rules (
    id                     bigint generated by default as identity,
    availability_period_id bigint not null,
    day_of_week            varchar(255) not null check (day_of_week in ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY')),
    start_time             time(6) not null,
    end_time               time(6) not null,
    created_at             timestamp(6) not null,
    primary key (id)
);

create table availability_overrides (
    id            bigint generated by default as identity,
    provider_id   bigint not null,
    override_date date not null,
    start_time    time(6) not null,
    end_time      time(6) not null,
    type          varchar(255) not null check (type in ('AVAILABLE', 'UNAVAILABLE')),
    created_at    timestamp(6) not null,
    primary key (id)
);

create table client_invitations (
    id          bigint generated by default as identity,
    provider_id bigint not null,
    email       varchar(255) not null,
    token       varchar(255) not null,
    invited_at  timestamp(6) not null,
    expires_at  timestamp(6) not null,
    primary key (id),
    constraint uk_client_invitations_email unique (email),
    constraint uk_client_invitations_token unique (token)
);

create table provider_invitations (
    id         bigint generated by default as identity,
    email      varchar(255) not null,
    token      varchar(255) not null,
    expires_at timestamp(6) not null,
    primary key (id),
    constraint uk_provider_invitations_email unique (email),
    constraint uk_provider_invitations_token unique (token)
);

create table provider_client_links (
    id          bigint generated by default as identity,
    provider_id bigint not null,
    client_id   bigint not null,
    invited_at  timestamp(6) not null,
    primary key (id)
);

-- Foreign keys
alter table user_profiles
    add constraint fk_user_profiles_user foreign key (user_id) references users;

alter table offerings
    add constraint fk_offerings_provider foreign key (provider_id) references users;

alter table appointments
    add constraint fk_appointments_provider foreign key (provider_id) references users;
alter table appointments
    add constraint fk_appointments_client foreign key (client_id) references users;
alter table appointments
    add constraint fk_appointments_offering foreign key (offering_id) references offerings;

alter table availability_periods
    add constraint fk_availability_periods_provider foreign key (provider_id) references users;

alter table availability_rules
    add constraint fk_availability_rules_period foreign key (availability_period_id) references availability_periods;

alter table availability_overrides
    add constraint fk_availability_overrides_provider foreign key (provider_id) references users;

alter table client_invitations
    add constraint fk_client_invitations_provider foreign key (provider_id) references users;

alter table provider_client_links
    add constraint fk_provider_client_links_provider foreign key (provider_id) references users;
alter table provider_client_links
    add constraint fk_provider_client_links_client foreign key (client_id) references users;