-- =====================================================================
-- Wellnara — Flyway V2 (step 3.1): financial wallet data model
--
-- Introduces the wallet module schema: wallets, an append-only ledger of
-- wallet_entries, and service_packages. Adds a currency column to providers
-- (users) and offerings. V1__baseline.sql is NOT modified.
--
-- Column types mirror Hibernate 6.5 / PostgreSQL output so that
-- ddl-auto=validate matches the entities on prod:
--   - identity PKs: bigint generated by default as identity
--   - money: numeric(10, 2)   - timestamps: timestamp(6)
--   - @Version: bigint not null   - enum: varchar(255) + check constraint
--
-- currency is added as nullable here (step 3.1 introduces the column only);
-- step 3.3 wires currency semantics and tightens nullability.
-- =====================================================================

-- --- currency on provider and offering ---------------------------------
alter table users
    add column currency varchar(3);

alter table offerings
    add column currency varchar(3);

-- --- wallets -----------------------------------------------------------
create table wallets (
    id          bigint generated by default as identity,
    client_id   bigint not null,
    provider_id bigint not null,
    currency    varchar(3) not null,
    version     bigint not null,
    created_at  timestamp(6) not null,
    primary key (id),
    constraint uk_wallets_client unique (client_id)
);

-- --- service packages --------------------------------------------------
create table service_packages (
    id             bigint generated by default as identity,
    wallet_id      bigint not null,
    offering_id    bigint not null,
    total_sessions integer not null,
    price          numeric(10, 2) not null,
    currency       varchar(3) not null,
    created_at     timestamp(6) not null,
    created_by     bigint not null,
    comment        varchar(1000),
    primary key (id)
);

-- --- append-only wallet ledger ----------------------------------------
create table wallet_entries (
    id                 bigint generated by default as identity,
    wallet_id          bigint not null,
    type               varchar(255) not null check (type in (
                           'TOP_UP', 'HOLD', 'RELEASE', 'SETTLE', 'ADJUSTMENT',
                           'PACKAGE_GRANT', 'PACKAGE_HOLD', 'PACKAGE_RELEASE', 'PACKAGE_CONSUME')),
    amount             numeric(10, 2),
    session_count      integer,
    currency           varchar(3) not null,
    service_package_id bigint,
    appointment_id     bigint,
    created_at         timestamp(6) not null,
    created_by         bigint not null,
    comment            varchar(1000),
    primary key (id)
);

-- --- foreign keys ------------------------------------------------------
alter table wallets
    add constraint fk_wallets_client foreign key (client_id) references users;
alter table wallets
    add constraint fk_wallets_provider foreign key (provider_id) references users;

alter table service_packages
    add constraint fk_service_packages_wallet foreign key (wallet_id) references wallets;
alter table service_packages
    add constraint fk_service_packages_offering foreign key (offering_id) references offerings;
alter table service_packages
    add constraint fk_service_packages_created_by foreign key (created_by) references users;

alter table wallet_entries
    add constraint fk_wallet_entries_wallet foreign key (wallet_id) references wallets;
alter table wallet_entries
    add constraint fk_wallet_entries_package foreign key (service_package_id) references service_packages;
alter table wallet_entries
    add constraint fk_wallet_entries_appointment foreign key (appointment_id) references appointments;
alter table wallet_entries
    add constraint fk_wallet_entries_created_by foreign key (created_by) references users;
