-- =====================================================================
-- Wellnara — Flyway V6: personal calendar subscription feed
--
-- One opaque, revocable token per user backs a read-only webcal/ICS feed
-- of that user's appointments. The token is a bearer secret; disabling a
-- subscription keeps the row (audit) but stops the feed from resolving.
--
-- Column types mirror Hibernate 6.5 / PostgreSQL output so ddl-auto=validate
-- matches the entity on prod:
--   - identity PK: bigint generated by default as identity
--   - timestamps: timestamp(6)
-- =====================================================================

create table calendar_subscriptions (
    id         bigint generated by default as identity,
    user_id    bigint not null,
    token      varchar(255) not null,
    enabled    boolean not null,
    created_at timestamp(6) not null,
    revoked_at timestamp(6),
    primary key (id),
    constraint uk_calendar_subscriptions_user unique (user_id),
    constraint uk_calendar_subscriptions_token unique (token)
);

alter table calendar_subscriptions
    add constraint fk_calendar_subscriptions_user foreign key (user_id) references users;
